### PR TITLE
Updated bundler

### PR DESCRIPTION
**Pull request by bitboxer**

### CODE REVIEW

**Comment by moonglum** [comment]
Hey :smile: Thanks for the PR! Travis complains:

```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.10.0) ruby

  Current Bundler version:
    bundler (1.7.6)
```

**Comment by bitboxer** [comment]
Ahhhhhhh....i hate bundler version stuff. Can we get rid of the version number all together?

**Comment by bitboxer** [comment]
I now removed the stupid version in there :wink:

**Comment by moonglum** [comment]
Thanks!

**Pull request merged**
