### PR TITLE
Release 1.0.0 :tada:

### PR DESCRIPTION
**Pull request by moonglum**
I think it is time for a release. And I think it's time for a 1.0.0, as this is running pretty smoothly now for quite some time :wink:

### CODE REVIEW

**Comment by moonglum** [comment]
@bitboxer Are you ok with it? :smile:

**Comment by bitboxer** [comment]
Of course. But I am curios if I am the only one left using it.

**Comment by moonglum** [comment]
I'm pretty certain that @thegcat is also using it!

**Comment by moonglum** [comment]
Released! :smile:

**Comment by thegcat** [comment]
I still do, though pretty infrequently, as I don't reinstall my machine that often :-)

Thanks!

**Pull request merged**
